from setuptools import setup, find_packages


setup(
    name='sage',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn[standard]>=0.24.0",
        "requests>=2.31.0",
        "pydantic>=2.0.0",
        "python-multipart>=0.0.6",
        "yt-dlp",
        "ffmpeg-python",
        "google-genai",
        "termcolor",
        "python-dateutil",
        "gradio==5.23.1",
        "google-cloud-storage",
        "google-search-results",
        "opencv-python",
        "transformers==4.57.0",
        "openai",
        "whisperx",
        "moviepy==2.1.2",
        "anthropic",
        "tqdm",
        "google-cloud-pubsub",
        "ipdb",
        "google-cloud-compute",
        "beautifulsoup4",
        "accelerate==1.10.1",
        # "bitsandbytes>=0.43.0",
        "black>=24.4.2",
        "datasets>=3.2.0",
        "distilabel[ray,openai]>=1.5.2",
        "einops>=0.8.0",
        "flake8>=6.0.0",
        "hf_transfer>=0.1.4",
        "huggingface-hub[cli]>=0.19.2,<1.0",
        "isort>=5.12.0",
        "math-verify",  # Used for math verification in grpo
        "packaging>=23.0",
        "parameterized>=0.9.0",
        "pytest",
        "safetensors>=0.3.3",
        "sentencepiece>=0.1.99",
        "wandb>=0.19.1",
        "pillow",
        "nltk",
        "rouge-score",
    ],
    author='Jitesh Jain',
    author_email='jitesh.jj2@gmail.com',
    description='A Workflow to understand YT videos',
    # long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/praeclarumjj3/soc_judge',
    classifiers=[
        'Programming Language :: Python :: 3.9',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)